version: '2'
services:
  wallabag:
    image: wallabag/wallabag:latest
    container_name: wallabag
    networks:
      - traefik
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.wallabag.loadbalancer.server.scheme=http"
      - "traefik.http.services.wallabag.loadbalancer.server.port=80"
      - "traefik.http.routers.wallabag.service=wallabag"
      - "traefik.http.routers.wallabag.rule=${DOCKER_ROUTER_RULE}"
    volumes:
      - './data/data:/var/www/wallabag/data:rw'
      - './data/image:/var/www/wallabag/web/assets/images:rw'
    env_file: .env

networks:
  traefik:
    external: true

