version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:80"
    environment:
      TZ: 'Asia/Shanghai'
      VIRTUAL_HOST: 'pi.hole'
      DNSMASQ_LISTENING: 'ALL' 
    volumes:
      - './data/etc-pihole:/etc/pihole'
      - './data/etc-dnsmasq.d:/etc/dnsmasq.d'
    dns:
      - 127.0.0.1
      - ${DEFAULT_DNS}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
