version: "3"

services:
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    command: redis-server
    networks:
      - backend
    volumes:
      - ./data:/data
      - ./config.local/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

networks:
  backend:
    external: true
