version: '2'
services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    networks:
      - traefik
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.nextcloud.loadbalancer.server.scheme=http"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.routers.nextcloud.rule=${DOCKER_ROUTER_RULE}"
    volumes:
      - './data:/var/www/html:rw'
    environment:
      TZ: Asia/Shanghai
    env_file: .env
    restart: unless-stopped

networks:
  traefik:
    external: true

