version: '3'

services:
  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare
    restart: unless-stopped
    networks:
      - cloudflare
    environment:
      TZ: Asia/Shanghai
    command: tunnel --no-autoupdate run --token ${TOKEN}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  cloudflare:
    external: true
