version: '3'

services:
  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - cloudflare
      - traefik
    environment:
      TZ: Asia/Shanghai
    command: tunnel --no-autoupdate run --token ${TOKEN}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  cloudflare:
    external: true
  traefik:
    external: true
