version: '3'

services:
  vaultwarden:
    user: ${DOCKER_USER}
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - cloudflare
    environment:
      ROCKET_PORT: 8080
      SIGNUPS_ALLOWED: "false"
      WEB_VAULT_ENABLED: "false"
      INVITATIONS_ALLOWED: "false"
      SHOW_PASSWORD_HINT: "false"
      DOMAIN: ${DOCKER_DOMAIN}
      TZ: Asia/Shanghai
    volumes:
      - ./data:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  cloudflare:
    external: true
