version: '3'

services:
  vaultwarden:
    user: ${DOCKER_USER}
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - cloudflare
    environment:
      WEBSOCKET_ENABLED: "true"  # Enable WebSocket notifications.
      ROCKET_PORT: 8080
      TZ: Asia/Shanghai
    volumes:
      - ./data:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  cloudflare:
    external: true
