version: "3"

services:
  db:
    container_name: db
    image: postgres:10.1-alpine
    restart: always
    expose:
      - 5432
    networks:
      - traefik
    volumes:
      - ${DOCKER_DATA_PATH}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:

networks:
  traefik:
    external: true
